export default {
  name: 'heroSection',
  title: 'Hero Section',
  type: 'document',
  __experimental_actions: ['update', 'publish'],
  fields: [
    {
      name: 'eyebrowLeft',
      title: 'Availability Badge (top left)',
      type: 'string',
      initialValue: 'Available for new commissions — Q2 booking open',
    },
    {
      name: 'eyebrowRight',
      title: 'Location Badge (top right)',
      type: 'string',
      initialValue: 'Lagos, NG · Worldwide',
    },
    {
      name: 'headlineLine1',
      title: 'Headline — Line 1',
      type: 'string',
      initialValue: 'Bold',
    },
    {
      name: 'headlineLine2',
      title: 'Headline — Line 2 (italic)',
      type: 'string',
      initialValue: 'graphic',
    },
    {
      name: 'headlineLine3',
      title: 'Headline — Line 3',
      type: 'string',
      initialValue: 'design',
    },
    {
      name: 'headlineLine4',
      title: 'Headline — Line 4',
      type: 'string',
      initialValue: 'that owns the wall.',
    },
    {
      name: 'blurb',
      title: 'Sub-headline / Blurb',
      type: 'text',
      rows: 3,
      initialValue: 'HBEE Designs is the studio of Habeeb — print, party flyers, promotional materials and brand visuals for clients who want to stop the scroll and turn heads in real life.',
    },
    {
      name: 'ctaPrimary',
      title: 'Primary CTA Button',
      type: 'string',
      initialValue: 'View portfolio',
    },
    {
      name: 'ctaSecondary',
      title: 'Secondary CTA Button',
      type: 'string',
      initialValue: 'Book a design',
    },
    {
      name: 'stat1Number',
      title: 'Stat 1 — Number',
      type: 'string',
      initialValue: '180+',
    },
    {
      name: 'stat1Label',
      title: 'Stat 1 — Label',
      type: 'string',
      initialValue: 'Designs delivered',
    },
    {
      name: 'stat2Number',
      title: 'Stat 2 — Number',
      type: 'string',
      initialValue: '40+',
    },
    {
      name: 'stat2Label',
      title: 'Stat 2 — Label',
      type: 'string',
      initialValue: 'Happy clients',
    },
    {
      name: 'stat3Number',
      title: 'Stat 3 — Number',
      type: 'string',
      initialValue: '6 yrs',
    },
    {
      name: 'stat3Label',
      title: 'Stat 3 — Label',
      type: 'string',
      initialValue: 'Studio practice',
    },
  ],
  preview: { prepare: () => ({ title: 'Hero Section' }) },
}
